# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)


1.21.6


In [3]:
print(np.show_config)

<function show at 0x7f70c461a290>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
x= np.zeros(10)

In [5]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array(★☆☆) 
(**hint**: size, itemsize)

In [6]:
memory = x.size* x.itemsize

In [7]:
memory

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [9]:
x= np.zeros(10)

In [10]:
x[4]= 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [11]:
x= np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [12]:
y= x[::-1]
y

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [13]:
x= np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
y= np.nonzero([1,2,0,0,4,0])
y

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [15]:
x= np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [16]:
x= np.random.random(27).reshape(3,3,3)
x

array([[[0.99931945, 0.29475535, 0.38444406],
        [0.2800263 , 0.79499701, 0.87971649],
        [0.95084427, 0.65917635, 0.74174091]],

       [[0.99863082, 0.80559966, 0.93756892],
        [0.26158836, 0.21643369, 0.5546791 ],
        [0.41119481, 0.49472528, 0.23496859]],

       [[0.79609416, 0.09673033, 0.12039871],
        [0.60230994, 0.16719184, 0.98499427],
        [0.19899245, 0.28741954, 0.92926157]]])

In [17]:
x= np.random.random((3,3,3))
x

array([[[0.95872146, 0.1498036 , 0.63759136],
        [0.97629187, 0.53217807, 0.36460453],
        [0.52838896, 0.32936013, 0.07042683]],

       [[0.85726129, 0.96675249, 0.53592216],
        [0.73304836, 0.96293572, 0.99790056],
        [0.2538215 , 0.80739097, 0.93586136]],

       [[0.27054291, 0.05535783, 0.56161137],
        [0.15516872, 0.50441377, 0.78793458],
        [0.1985856 , 0.92692339, 0.72618191]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [18]:
x= np.random.random((10, 10))

In [19]:
a= x.min()
b= x.max()
print(a,b)

0.01812511021527985 0.9700282327460716


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [20]:
x= np.random.random(30)
x.mean()

0.6198654728370251

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [21]:
x= np.ones((3,3))

In [22]:
x[1:-1, 1:-1]= 0
x

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [23]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
x= np.pad(x, pad_width= 1, mode= 'constant',constant_values= 0 )
x

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [26]:
x= np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
x= np.diag(np.arange(1,5), k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [28]:
x=np.ones((8,8), dtype= int)

In [29]:
x[1::2,::2]= 0
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [30]:
x= np.ones((6,7,8))

In [31]:
np.unravel_index(99, shape = (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [32]:
x= np.tile(([1,0],[0,1]), (4,4))
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [33]:
x= np.random.random((5,5))

In [34]:
x= (x- x.min())/(x.max()- x.min())
x

array([[0.66942553, 0.52481681, 0.27073629, 0.23220021, 0.97849234],
       [0.        , 0.36003744, 0.68516267, 0.55633688, 0.35262307],
       [0.25877615, 0.92401186, 1.        , 0.18304918, 0.9413171 ],
       [0.36786928, 0.44095708, 0.98952223, 0.14050332, 0.70457755],
       [0.82260637, 0.58428118, 0.03343577, 0.02981015, 0.38247704]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [35]:
RGBA = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte),])

In [36]:
RGBA

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [37]:
x= np.random.random((5,3))
y= np.random.random((3,2))

In [38]:
z= np.dot(x,y)
z

array([[0.6551406 , 0.63342258],
       [0.59894107, 1.06668287],
       [0.61588153, 0.72585588],
       [0.68995624, 1.08130038],
       [0.9662891 , 1.28972311]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [39]:
x= np.arange(15)
x[(x>3) & (x<8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [40]:
print(sum(range(5),-1))

9


In [41]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:
Z= 3

In [43]:
Z**Z


27

In [44]:
2 << Z >> 2


4

In [45]:
Z <- Z

False

In [46]:
1j*Z


3j

In [47]:
Z/1/1

3.0

In [48]:
Z<Z>Z

False

All the above expressions are legal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
np.array(0) / np.array(0)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [50]:
np.array(0) // np.array(0)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [51]:
np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [52]:
x= np.random.random((3,3))
y=x= np.random.random((3,3))
print(np.intersect1d(x,y))

[0.23604339 0.35874442 0.64729082 0.69960097 0.7562339  0.75977147
 0.8221642  0.93600449 0.98847683]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [53]:
#data to check warnings
data = np.random.random(1000).reshape(10, 10,10) * np.nan

In [54]:
#ignoring warnings
np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [55]:
#checking for warnings
np.nanmedian(data, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [56]:
with np.errstate(divide='warn'):
  np.nanmedian(data, axis=[1, 2])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [57]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

Well, no it isn't true. It is False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [58]:
yesterday = np.datetime64('today')- np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today')+ np.timedelta64(1)
print( yesterday, today, tomorrow)

2022-10-26 2022-10-27 2022-10-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [59]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [60]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A,B)

[1. 1. 1.] [2. 2. 2.]


In [61]:
#A or B both are same here, going for B since we will use A
np.add(A,B,out=B)

array([3., 3., 3.])

In [62]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [63]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [64]:
#A or B for out don't matter 
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [65]:
x= np.random.uniform(0,5,5)
x

array([4.74084613, 1.30320621, 4.23451551, 1.45320352, 4.31614781])

In [66]:
#1
y= x.astype(int)
y

array([4, 1, 4, 1, 4])

In [67]:
#2
y= x//1
y

array([4., 1., 4., 1., 4.])

In [68]:
#3
y= np.trunc(x)
y

array([4., 1., 4., 1., 4.])

In [69]:
#4
y= x-x%1
y

array([4., 1., 4., 1., 4.])

In [70]:
#5
y= np.floor(x)
y

array([4., 1., 4., 1., 4.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [71]:
x= np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
y= np.arange(5)
y

array([0, 1, 2, 3, 4])

In [73]:
x= x+y
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [74]:
#yield keyword is used to create a generator function.
def generator():
  for i in range(10):
    yield i

In [75]:
generator()    

<generator object generator at 0x7f70b667e950>

In [76]:
x= np.fromiter(generator(), dtype=float, count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [77]:
x=np.linspace(0,1, num=10, endpoint= False)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [78]:
x= x[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [79]:
x=np.random.rand(10)
x

array([0.62829886, 0.65262786, 0.12312166, 0.60935333, 0.50492291,
       0.57994463, 0.13591478, 0.44467807, 0.24801074, 0.98363193])

In [80]:
x.sort()
x

array([0.12312166, 0.13591478, 0.24801074, 0.44467807, 0.50492291,
       0.57994463, 0.60935333, 0.62829886, 0.65262786, 0.98363193])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [81]:
#not random
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [83]:
#random
A= np.random.random(10)
B= np.random.random(10)
print(A,B)

[0.43304636 0.22799661 0.30839982 0.72824543 0.02021547 0.0668392
 0.77580118 0.98663341 0.7933764  0.98868737] [0.16581375 0.77390861 0.8541763  0.47871707 0.57247027 0.05377342
 0.84048565 0.54274693 0.38683431 0.26131319]


In [84]:
x_equal= np.allclose(A,B)
print(x_equal)

False


In [85]:
y_equal= np.array_equal(A,B)
print(y_equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [86]:
x= np.ones(5)
x.flags.writeable= False

In [87]:
#x[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [88]:
a= np.random.random((10,2))
a

array([[0.36555343, 0.66958374],
       [0.87979006, 0.98559749],
       [0.80221522, 0.85828024],
       [0.88264865, 0.07270265],
       [0.35810141, 0.18221438],
       [0.74133914, 0.11597749],
       [0.52667153, 0.54199679],
       [0.95952823, 0.85366131],
       [0.12398613, 0.91640075],
       [0.08464858, 0.24871201]])

In [89]:
x,y= a[:,0], a[:,1]

In [90]:
r= np.sqrt(x**2)+y**2
t= np.arctan2(y,x)
print(r,t)

[0.81389582 1.85119247 1.5388602  0.88793433 0.39130349 0.75478992
 0.82043205 1.68826587 0.96377647 0.14650624] [1.07107452 0.84205887 0.81914937 0.0821832  0.47069026 0.15518537
 0.7997377  0.72707725 1.43631608 1.24274612]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [91]:
x= np.random.random(10)
x[np.argmax(x)]=0

In [92]:
x

array([0.88821215, 0.59155067, 0.84517624, 0.        , 0.11237389,
       0.98396761, 0.59528871, 0.66790017, 0.18831997, 0.38439722])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [93]:
a= np.zeros((5,5), [('x', float), ('y', float)])
a

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [96]:
a['x'], a['y']= np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [97]:
x= np.arange(10)
y= x+0.7

In [98]:
c= 1/(np.subtract.outer(x,y))
c

array([[-1.42857143, -0.58823529, -0.37037037, -0.27027027, -0.21276596,
        -0.1754386 , -0.14925373, -0.12987013, -0.11494253, -0.10309278],
       [ 3.33333333, -1.42857143, -0.58823529, -0.37037037, -0.27027027,
        -0.21276596, -0.1754386 , -0.14925373, -0.12987013, -0.11494253],
       [ 0.76923077,  3.33333333, -1.42857143, -0.58823529, -0.37037037,
        -0.27027027, -0.21276596, -0.1754386 , -0.14925373, -0.12987013],
       [ 0.43478261,  0.76923077,  3.33333333, -1.42857143, -0.58823529,
        -0.37037037, -0.27027027, -0.21276596, -0.1754386 , -0.14925373],
       [ 0.3030303 ,  0.43478261,  0.76923077,  3.33333333, -1.42857143,
        -0.58823529, -0.37037037, -0.27027027, -0.21276596, -0.1754386 ],
       [ 0.23255814,  0.3030303 ,  0.43478261,  0.76923077,  3.33333333,
        -1.42857143, -0.58823529, -0.37037037, -0.27027027, -0.21276596],
       [ 0.18867925,  0.23255814,  0.3030303 ,  0.43478261,  0.76923077,
         3.33333333, -1.42857143, -0.58823529

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [100]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [101]:
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [108]:
np.set_printoptions(threshold=float('inf'))
x= np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [111]:
x= np.arange(10)
y= np.random.uniform(0,10)
print(x,y)

[0 1 2 3 4 5 6 7 8 9] 6.443845394321091


In [112]:
index= (np.abs(x-y)).argmin()
print(x[index])

6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [114]:
x= np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]),
                 ('color', [('r', float, 1), ('g', float, 1),('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [117]:
a= np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
print(x, y)

[[0.20566484 0.66448867 0.23566103 0.26426657 0.9634051  0.68218505
  0.6794048  0.23587134 0.79214827 0.50193744 0.56209546 0.43842366
  0.26279004 0.25124765 0.70262481 0.05249329 0.34341372 0.03711624
  0.98236371 0.4954918  0.91614178 0.26937775 0.55834798 0.3524867
  0.68000906 0.65916204 0.82538067 0.38092904 0.79977868 0.5512058
  0.38144824 0.49888498 0.78888479 0.36229634 0.65970708 0.84230856
  0.54721905 0.92332901 0.89458693 0.77725701 0.80361193 0.43990715
  0.70412448 0.41081704 0.16705293 0.0949004  0.85079986 0.91193398
  0.82314695 0.14841172 0.15096871 0.60023933 0.48665077 0.9297537
  0.38882261 0.70723647 0.1682954  0.42358091 0.29274516 0.10581569
  0.39199205 0.87239318 0.91125725 0.9271814  0.51854438 0.51374096
  0.37818674 0.87208475 0.61888757 0.46123168 0.95693639 0.9360139
  0.27491539 0.83654813 0.65631    0.95248507 0.74204714 0.43018177
  0.36644862 0.5139322  0.30110857 0.53164414 0.87975748 0.65136653
  0.38968146 0.42172309 0.67313335 0.5552144  0.0749

In [118]:
b= np.sqrt((x-x.T)**2 +(y-y.T)**2)
print(b)

[[0.         0.47520637 0.43626959 0.18696838 0.81686827 0.64528487
  0.78385964 0.37296734 0.67596586 0.68709266 0.36328062 0.74442826
  0.19924369 0.0654861  0.57119509 0.20559045 0.16060236 0.17718169
  1.03000896 0.29753557 0.88890529 0.28116819 0.35696419 0.52932558
  0.58358798 0.45456406 0.9362314  0.21662786 0.60305893 0.50615943
  0.77378188 0.59827581 0.86636837 0.15771178 0.45601502 0.99804701
  0.76194052 1.00867298 0.72530258 0.7507221  0.70179888 0.791654
  0.6398739  0.27166564 0.17441297 0.67727645 0.92000971 0.82988643
  0.6189857  0.13081884 0.38691372 0.4222964  0.69969466 0.93001141
  0.57554891 0.50953783 0.46777844 0.50052279 0.4340971  0.55311637
  0.38033676 0.67898253 0.72569264 0.91688591 0.31780003 0.33016253
  0.17326035 0.69079043 0.52523242 0.33775329 0.8335547  0.73443455
  0.46730035 0.63612937 0.81064186 0.88906804 0.65721909 0.3026429
  0.17235263 0.30909798 0.29043337 0.82835961 0.72587107 0.85946961
  0.19172634 0.38676756 0.79031369 0.42758091 0.667

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [124]:
x= (np.random.rand(5,5).astype(np.float32))
x

array([[0.9875232 , 0.96449065, 0.02964498, 0.8544226 , 0.40364936],
       [0.68313295, 0.06843974, 0.7641391 , 0.7528214 , 0.6102886 ],
       [0.11537481, 0.9678608 , 0.09941304, 0.8067233 , 0.04826651],
       [0.407888  , 0.17691171, 0.02930418, 0.2626836 , 0.45718598],
       [0.9838822 , 0.39246345, 0.31156287, 0.7880175 , 0.81398606]],
      dtype=float32)

In [126]:
y= x.view(np.int32)
y[:]= x
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [127]:
from io import StringIO
s= StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')

In [128]:
x= np.genfromtxt(s, delimiter= ',', dtype= np.int)
x

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [129]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [131]:
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [132]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
sigma, mu= 1.0, 0
Z= ( ((np.sqrt(x*x+y*y))-mu)**2 / ( 2.0 * sigma**2 ) ) 
G= np.exp(-Z)
G

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [133]:
n = 10
p = 3
Z = np.zeros((n,n))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [136]:
X = np.random.rand(5, 10)
X

array([[0.61452003, 0.54440175, 0.13673251, 0.36355696, 0.99317395,
        0.39396694, 0.58828443, 0.68212925, 0.59032344, 0.54375852],
       [0.84378321, 0.81783686, 0.49935156, 0.79537532, 0.13703924,
        0.59473111, 0.39412572, 0.03034168, 0.36025575, 0.26214498],
       [0.46033543, 0.16783779, 0.94183841, 0.35020528, 0.28816449,
        0.46475877, 0.93218758, 0.75117235, 0.28154542, 0.69042009],
       [0.23306807, 0.89791593, 0.95344423, 0.27123534, 0.35492129,
        0.25037137, 0.85772556, 0.07916275, 0.6676385 , 0.05938415],
       [0.71933853, 0.93497015, 0.32406702, 0.36871802, 0.40464703,
        0.44803665, 0.67477115, 0.23564477, 0.21406996, 0.17533037]])

In [137]:
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.06943525, -0.00068303, -0.40835227, -0.18152782,  0.44808917,
        -0.15111784,  0.04319965,  0.13704447,  0.04523867, -0.00132626],
       [ 0.37028467,  0.34433832,  0.02585301,  0.32187678, -0.3364593 ,
         0.12123256, -0.07937282, -0.44315687, -0.11324279, -0.21135356],
       [-0.07251113, -0.36500877,  0.40899185, -0.18264129, -0.24468207,
        -0.06808779,  0.39934102,  0.21832579, -0.25130114,  0.15757353],
       [-0.22941865,  0.43542921,  0.49095751, -0.19125138, -0.10756543,
        -0.21211535,  0.39523884, -0.38332397,  0.20515178, -0.40310257],
       [ 0.26937917,  0.48501079, -0.12589235, -0.08124134, -0.04531234,
        -0.00192272,  0.22481179, -0.2143146 , -0.23588941, -0.274629  ]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [138]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[6 8 9]
 [1 6 5]
 [8 9 5]]


In [140]:
print(Z[Z[:,2].argsort()])

[[1 6 5]
 [8 9 5]
 [6 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [142]:
Z = np.random.randint(0,3,(3,10))
Z

array([[1, 2, 0, 0, 2, 2, 1, 0, 2, 1],
       [2, 2, 2, 1, 0, 0, 2, 2, 0, 0],
       [0, 2, 1, 0, 1, 1, 0, 1, 1, 1]])

In [144]:
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
Z

array([[ 0.,  1., nan],
       [ 1.,  2., nan],
       [ 4.,  5., nan]])

In [145]:
print(np.isnan(Z).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [146]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5063138030830928


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [147]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

In [150]:
it = np.nditer([A,B,None])

In [158]:
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [159]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [167]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [168]:
I = np.random.randint(0,len(Z),20)
print(I)

[6 8 8 3 8 1 7 4 4 0 5 5 7 5 0 0 7 8 6 3]


In [170]:
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 1. 3. 3. 4. 3. 4. 5. 1.]


In [171]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 6. 1. 3. 3. 2. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [172]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

In [173]:
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [186]:
w, h = 500,500
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
print(len(I))

500


In [187]:
colors = np.unique(I.reshape(-1, 3), axis=0)
print(len(colors))

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [188]:
A = np.random.randint(0,10,(3,4,3,4))
A

array([[[[1, 6, 9, 7],
         [3, 4, 8, 0],
         [1, 7, 2, 1]],

        [[0, 4, 1, 2],
         [1, 1, 1, 1],
         [1, 9, 5, 8]],

        [[6, 1, 4, 3],
         [2, 6, 2, 9],
         [2, 8, 8, 8]],

        [[2, 7, 1, 5],
         [7, 8, 3, 4],
         [6, 6, 6, 2]]],


       [[[3, 5, 8, 5],
         [0, 0, 4, 0],
         [6, 5, 0, 5]],

        [[6, 3, 2, 5],
         [3, 5, 4, 3],
         [4, 3, 7, 9]],

        [[1, 8, 1, 0],
         [1, 9, 4, 2],
         [7, 6, 7, 2]],

        [[4, 3, 8, 5],
         [1, 2, 0, 1],
         [7, 4, 8, 8]]],


       [[[1, 4, 1, 4],
         [0, 2, 7, 8],
         [3, 3, 3, 7]],

        [[2, 6, 2, 8],
         [6, 5, 9, 6],
         [7, 8, 0, 7]],

        [[5, 3, 8, 1],
         [8, 0, 2, 5],
         [7, 6, 6, 3]],

        [[4, 4, 2, 3],
         [9, 5, 5, 3],
         [6, 5, 1, 3]]]])

In [189]:
sum = A.sum(axis=(-2,-1))
print(sum)

[[49 34 59 57]
 [41 54 48 51]
 [43 66 54 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [191]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100) #subset so repeating
print(D,S)

[0.78950807 0.16196425 0.84797237 0.83757681 0.35073782 0.26817529
 0.14070123 0.10746    0.6846508  0.43456061 0.09624017 0.11493175
 0.99157061 0.69144301 0.48140069 0.30732696 0.36432281 0.41256194
 0.41234469 0.72919838 0.33896514 0.05820576 0.80685481 0.73558279
 0.72577357 0.87187274 0.97495383 0.29736043 0.95967733 0.08616006
 0.15811859 0.53796244 0.55173246 0.45088189 0.62032298 0.22746744
 0.64208898 0.86265741 0.80155892 0.56753556 0.17670906 0.95320892
 0.28827661 0.82043082 0.04312137 0.42910091 0.60116961 0.77577938
 0.69586339 0.68277175 0.12866232 0.58378552 0.22856757 0.94865451
 0.27049838 0.91710725 0.52550694 0.14484626 0.06701118 0.36959059
 0.34076774 0.37046125 0.70315271 0.96777278 0.21545664 0.14489023
 0.80640323 0.24287191 0.36070977 0.82759634 0.39591827 0.33087172
 0.93284387 0.25008861 0.3145717  0.63041062 0.42287112 0.68190146
 0.41799353 0.76704682 0.50263597 0.8674007  0.44780855 0.37528022
 0.63542266 0.38949005 0.30482813 0.16558743 0.79200564 0.1889

In [192]:
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
print(D_sums, D_counts)

[ 3.67505875  2.83435694  6.18680032  2.38679249  6.16911889 11.00911144
  4.60412181  5.02000495  4.71431838  4.45373754] [ 8  4 11  5 11 22 10 12  8  9]


In [193]:
D_means = D_sums / D_counts
print(D_means)

[0.45938234 0.70858924 0.56243639 0.4773585  0.56082899 0.50041416
 0.46041218 0.41833375 0.5892898  0.49485973]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [194]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

array([63, 41, 87])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [195]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*3)
Z0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [196]:
Z0[::3+1] = Z #every 4th position starting from 1st
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [197]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [198]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [199]:
faces = np.random.randint(0,100,(10,3))
faces

array([[57, 41,  4],
       [87, 82, 66],
       [89, 24, 51],
       [48, 74, 57],
       [77, 70, 91],
       [27, 81, 89],
       [42, 94, 58],
       [57, 73,  9],
       [91, 87,  8],
       [ 2, 63, 31]])

In [200]:
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 31) ( 2, 63) ( 4, 41) ( 4, 57) ( 8, 87) ( 8, 91) ( 9, 57) ( 9, 73)
 (24, 51) (24, 89) (27, 81) (27, 89) (31, 63) (41, 57) (42, 58) (42, 94)
 (48, 57) (48, 74) (51, 89) (57, 73) (57, 74) (58, 94) (66, 82) (66, 87)
 (70, 77) (70, 91) (77, 91) (81, 89) (82, 87) (87, 91)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [201]:
C = np.bincount([1,1,2,3,4,4,6])
C

array([0, 2, 1, 1, 2, 0, 1])

In [202]:
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [207]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [209]:
Z = np.arange(20)
print(np.cumsum(Z, dtype=float))
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [210]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [211]:
#boolean
Z = np.random.randint(0,2,100)
Z

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0])

In [212]:
print(np.logical_not(Z, out=Z))

[0 0 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0
 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 0 1
 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1]


In [213]:
#float
Z = np.random.uniform(-1.0,1.0,10)
Z

array([ 0.45359734,  0.48820815, -0.13780226, -0.41464438,  0.30830237,
       -0.97234763,  0.297708  ,  0.95519429,  0.38973726,  0.59370716])

In [214]:
print(np.negative(Z, out=Z))

[-0.45359734 -0.48820815  0.13780226  0.41464438 -0.30830237  0.97234763
 -0.297708   -0.95519429 -0.38973726 -0.59370716]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [215]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

In [216]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.94736086 10.97664703  3.6872653   4.4701707   0.03656875 16.83261763
  6.45338832  0.17699583 11.0695005   0.761773  ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [229]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.32400860e+01 7.34809694e+00 2.46190558e+00 6.86867503e+00
  1.56258905e+00 8.34331271e+00 1.61328434e+00 1.57170070e+01
  1.73468618e+00 5.92561812e+00]
 [3.55924315e+00 1.93140806e+01 6.18009616e+00 6.05745378e+00
  9.32438636e+00 1.16566696e+00 2.24032029e+00 1.92029462e+01
  3.56034869e-01 2.61488539e+00]
 [1.35867067e+01 8.51242333e+00 1.27634729e+00 6.88200264e+00
  3.81029213e-01 8.89003588e+00 5.14956100e-01 1.68044383e+01
  7.19786333e-01 6.71983637e+00]
 [6.84316416e+00 5.08812548e+00 9.95487253e+00 1.23037867e+01
  5.69710573e+00 1.14735964e+01 1.46413246e+01 2.33537365e+00
  1.69716282e+01 1.24320275e+01]
 [3.55510269e+00 5.47291880e+00 8.71423272e+00 9.16901397e+00
  5.00560758e+00 8.22645082e+00 1.24968754e+01 4.53749028e+00
  1.44671314e+01 9.42021171e+00]
 [6.74640926e+00 1.65774920e+01 4.46399415e+00 2.14132870e+00
  6.92687115e+00 3.74753170e+00 1.90531318e+00 1.89708118e+01
  6.15994255e-03 4.21514885e+00]
 [3.61546436e+00 1.75589093e+01 4.54771551e+00 5.50667501e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [230]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 5 2 3 5 0 0 7 7 7]
 [5 5 0 2 7 4 0 9 5 6]
 [9 3 6 2 0 2 9 4 7 6]
 [5 9 2 7 4 2 9 8 2 5]
 [0 8 3 7 9 2 5 9 7 1]
 [2 6 3 8 3 4 7 7 7 6]
 [5 9 1 9 7 7 5 7 8 5]
 [8 0 3 0 2 9 4 0 0 9]
 [1 7 2 8 6 6 8 1 5 3]
 [9 7 5 5 3 8 4 8 8 0]]
[[0 0 0 0 0]
 [0 7 5 2 3]
 [0 5 5 0 2]
 [0 9 3 6 2]
 [0 5 9 2 7]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [232]:
Z = np.arange(1,15,dtype=int)
Z.size

14

In [236]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

In [237]:
R = rolling(Z, 4)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [239]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition

In [240]:
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [241]:
Z = np.random.randint(0,10,50)
Z

array([3, 6, 4, 2, 2, 8, 7, 0, 7, 3, 5, 2, 8, 0, 9, 3, 4, 2, 9, 6, 1, 3,
       4, 1, 4, 6, 7, 8, 3, 2, 2, 2, 3, 4, 1, 0, 0, 2, 2, 1, 3, 5, 6, 8,
       3, 4, 9, 1, 6, 6])

In [243]:
print('value:', np.bincount(Z).argmax())

value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [244]:
Z = np.random.randint(0,5,(6,6))
Z

array([[2, 2, 4, 0, 0, 1],
       [1, 2, 1, 4, 3, 1],
       [2, 4, 1, 0, 2, 1],
       [3, 0, 2, 4, 3, 0],
       [2, 4, 0, 3, 1, 1],
       [1, 4, 2, 2, 0, 1]])

In [245]:
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 4]
   [1 2 1]
   [2 4 1]]

  [[2 4 0]
   [2 1 4]
   [4 1 0]]

  [[4 0 0]
   [1 4 3]
   [1 0 2]]

  [[0 0 1]
   [4 3 1]
   [0 2 1]]]


 [[[1 2 1]
   [2 4 1]
   [3 0 2]]

  [[2 1 4]
   [4 1 0]
   [0 2 4]]

  [[1 4 3]
   [1 0 2]
   [2 4 3]]

  [[4 3 1]
   [0 2 1]
   [4 3 0]]]


 [[[2 4 1]
   [3 0 2]
   [2 4 0]]

  [[4 1 0]
   [0 2 4]
   [4 0 3]]

  [[1 0 2]
   [2 4 3]
   [0 3 1]]

  [[0 2 1]
   [4 3 0]
   [3 1 1]]]


 [[[3 0 2]
   [2 4 0]
   [1 4 2]]

  [[0 2 4]
   [4 0 3]
   [4 2 2]]

  [[2 4 3]
   [0 3 1]
   [2 2 0]]

  [[4 3 0]
   [3 1 1]
   [2 0 1]]]]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [247]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

In [248]:
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6  8 10 15]
 [ 6  4 11  7  4]
 [ 8 11  8 42 13]
 [10  7 42  5 11]
 [15  4 13 11  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [249]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [250]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [251]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [256]:
Z = np.arange(10000)
np.random.shuffle(Z)

In [257]:
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [258]:
print (Z[np.argpartition(-Z,n)[:n]])

[9996 9997 9998 9999 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [259]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [264]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Z

array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U32')

In [265]:
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [268]:
Z= np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

3.75 s ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
152 ms ± 21.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
124 ms ± 5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [269]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [ ]:
C = (A[..., np.newaxis, np.newaxis] == B)
C

In [271]:
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [274]:
Z = np.random.randint(0,5,(10,3))
print(Z)

[[1 3 3]
 [1 0 3]
 [1 1 1]
 [4 1 3]
 [3 4 4]
 [1 1 2]
 [4 3 4]
 [3 0 2]
 [0 0 2]
 [2 1 0]]


In [275]:
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[1 3 3]
 [1 0 3]
 [4 1 3]
 [3 4 4]
 [1 1 2]
 [4 3 4]
 [3 0 2]
 [0 0 2]
 [2 1 0]]


In [276]:
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 3 3]
 [1 0 3]
 [4 1 3]
 [3 4 4]
 [1 1 2]
 [4 3 4]
 [3 0 2]
 [0 0 2]
 [2 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [277]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [278]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [279]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.33359618, 0.54175982, 0.3000533 , 0.1613965 , 0.28233669,
        0.10131974, 0.30200663, 0.25857319, 0.4485516 , 0.19456345],
       [0.06688206, 0.10861638, 0.06015711, 0.03235807, 0.05660514,
        0.0203134 , 0.06054873, 0.05184084, 0.08992925, 0.03900765],
       [0.18176942, 0.29519334, 0.16349262, 0.0879415 , 0.15383922,
        0.05520696, 0.16455695, 0.140891  , 0.24440617, 0.10601346],
       [0.33137463, 0.53815203, 0.29805513, 0.1603217 , 0.2804565 ,
        0.10064501, 0.29999546, 0.25685125, 0.44556452, 0.19326778],
       [0.49725596, 0.80754312, 0.4472572 , 0.24057642, 0.42084894,
        0.15102645, 0.45016882, 0.38542725, 0.66860764, 0.29001482],
       [0.43123459, 0.70032449, 0.38787424, 0.20863475, 0.36497224,
        0.13097445, 0.39039928, 0.33425354, 0.57983567, 0.25150915],
       [0.3883258 , 0.63064065, 0.34927989, 0.18787513, 0.3286567 ,
        0.11794221, 0.35155369, 0.30099457, 0.52214074, 0.22648343],
       [0.30249048, 0.4912442 , 0.2720752

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [280]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [281]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [282]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [5, 95])
print(confint)

[-0.16472907  0.1532377 ]
